coverage:
  status:
    project:
      disma:
        target: auto
        threshold: 3%
        flags:
          - disma
      disma-cli:
        target: auto
        threshold: 3%
        flags:
          - disma-cli
flag_management:
  individual_flags:
    - name: disma
      paths:
        - "disma/.*"
      carryforward: true
    - name: disma-cli
      paths:
        - "disma-cli/.*"
      carryforward: true
ignore:
  - disma/src/tests
