coverage:
  status:
    project:
      disma:
        target: auto
        threshold: 2
        flags:
          - disma
      disma-cli:
        target: auto
        threshold: 2
        flags:
          - disma-cli
flag_management:
  individual_flags:
    - name: disma
      paths:
        - disma/target/coverage/coverage.info
      carryforward: true
    - name: disma-cli
      paths:
        - disma-cli/target/coverage/coverage.info
      carryforward: true
