on:
  workflow_call:
    inputs:
      package:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            **/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('./Cargo.lock') }}

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy

      - name: Lint
        run: ../ci/lint.sh ${{ inputs.package }}
        working-directory: ${{ inputs.package }}

      - name: Build
        run: cargo build
        working-directory: ${{ inputs.package }}

      - name: Test
        run: cargo test
        working-directory: ${{ inputs.package }}
