name: Build

on:
  push:
    branches:
      - "master"
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  disma:
    uses: vigenere23/disma/.github/workflows/build.template.yml@chore/coveralls
    with:
      package: disma

  disma-cli:
    needs: disma
    uses: vigenere23/disma/.github/workflows/build.template.yml@chore/coveralls
    with:
      package: disma-cli
