on:
  workflow_call:
    inputs:
      package:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      RUSTFLAGS: -C instrument-coverage
      LLVM_PROFILE_FILE: target/coverage/raw/%p-%m.profraw

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            **/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('./Cargo.lock') }}

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy, llvm-tools-preview

      - name: Lint
        run: ../scripts/lint.sh ${{ inputs.package }}
        working-directory: ${{ inputs.package }}

      - name: Build
        run: cargo build
        working-directory: ${{ inputs.package }}

      - name: Test
        run: cargo test
        working-directory: ${{ inputs.package }}

      - name: Install Coverage tools
        run: |
          export RUST_ARCH="$(rustc -vV | sed -n 's|host: ||p')"
          wget -c "https://github.com/mozilla/grcov/releases/download/v0.8.13/grcov-$RUST_ARCH.tar.bz2" -O - | tar -xj -C ~/.cargo/bin

      - name: Generate coverage
        run: ./scripts/coverage/generate.sh ${{ inputs.package }} ci

      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash) -F ${{ inputs.package }}

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          base-path: ${{ inputs.package }}
          flag-name: ${{ inputs.package }}
          path-to-lcov: ${{ inputs.package }}/target/coverage/coverage.info
