name: Deploy (on master)

on:
  push:
    branches:
      - "master"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  disma_build:
    name: disma:build
    uses: ./.github/workflows/build.template.yml
    with:
      package: disma

  disma-cli_build:
    name: disma-cli:build
    needs: disma_build
    uses: ./.github/workflows/build.template.yml
    with:
      package: disma-cli

  build-website:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: site

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: "18.13.0"
          cache: "pnpm"
          cache-dependency-path: "site/pnpm-lock.yaml"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build --base=/disma

      - name: Upload artifact for Github Pages
        uses: actions/upload-pages-artifact@v3
        with:
          name: build
          path: site/dist

  deploy-website:
    needs: build-website
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to Github Pages
        uses: actions/deploy-pages@v4
        with:
          artifact_name: build
          timeout: "100000"
