name: Deploy (on tag)

on:
  push:
    tags:
      - "*/v*.*.*"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  disma_build:
    name: disma:build
    uses: ./.github/workflows/build.template.yml
    with:
      package: disma

  disma-cli_build:
    name: disma-cli:build
    needs: disma_build
    uses: ./.github/workflows/build.template.yml
    with:
      package: disma-cli

  disma_publish-crate:
    name: disma:publish-crate
    needs: disma_build
    uses: ./.github/workflows/publish.template.yml
    with:
      package: disma
    secrets: inherit

  disma-cli_publish-crate:
    name: disma-cli:publish-crate
    needs: [disma-cli_build, disma_publish-crate]
    uses: ./.github/workflows/publish.template.yml
    with:
      package: disma-cli
    secrets: inherit

  disma-cli_github_release:
    name: disma-cli:github-release
    needs: disma-cli_publish-crate
    uses: ./.github/workflows/release.template.yml
    with:
      package: disma-cli
      binary: disma
    secrets: inherit
