name: Publish

on:
  push:
    tags:
      - "*/v*.*.*"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  disma:
    uses: vigenere23/disma/.github/workflows/publish.template.yml@master
    with:
      package: disma
    secrets: inherit

  disma-cli:
    needs: disma
    uses: vigenere23/disma/.github/workflows/publish.template.yml@master
    with:
      package: disma-cli
    secrets: inherit
